### ISSUE TITLE
Question regarding zero-shot inference settings

### ISSUE THREAD

**Issue by Jawing** [microsoft/RegionCLIP#9]
Questions regarding the settings added below in zero-shot inferences. Could I get an explanation for each one of them? I notice in `test_transfer_learning.sh` these settings aren't included. They are again included for `test_zeroshot_inference.sh` and both `visualize*.sh` which doesn't make sense to me. When these settings are turned on I am getting a lower AP scores as well when evaluating `test_transfer_learning.sh`
```
MODEL:
  ROI_HEADS:
    NMS_THRESH_TEST: 0.5
  CLIP:
    NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
```
